services:
  mysql: 
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'classicmodels'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
  pythonapp:
    build: ./
    depends_on:
      - mysql